Fixed issue with language labels on messages and banners page.
CeON/fairchive pull request #107
Opened 2019-04-24 08:23 UTC by MrK191

2019-04-24 11:43 UTC, madryk requested changes
We should show to the user only license languages that are defined in system property

2019-04-24 14:37 UTC, MrK191 commented
+ Moved settingsWrapper to settings package.

2019-04-24 15:43 UTC, madryk requested changes

2019-04-24 15:43 UTC, madryk commented on src/main/webapp/dataverse-textMessages.xhtml
> +                                                           value="#{bundle[localbanner.locale]}:"
This won't work like an original solution - that is returning language translated to language of current localized banner: "polski", "english" etc.

2019-04-24 15:43 UTC, madryk commented on src/main/webapp/dataverse-textMessages.xhtml
> +                                            <h:outputLabel for="message" value="#{bundle[localmessage.locale]}:"
same as above

2019-04-24 15:43 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/bannersandmessages/messages/LazyDataverseTextMessage.java
> +    private List<DataverseTextMessageDto> removedMessageLangugaesNotPresentInDataverse(List<DataverseTextMessageDto> dataList) {
`removeMessageLanguages...`

2019-04-24 15:43 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/bannersandmessages/banners/LazyBannerHistory.java
> +    private List<DataverseBannerDto> removedBannersLangugaesNotPresentInDataverse(List<DataverseBannerDto> dataList) {
`removeBannerLanguages...`

2019-04-25 11:48 UTC, madryk requested changes

2019-04-25 11:48 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/bannersandmessages/banners/LazyBannerHistory.java
> +    private List<DataverseBannerDto> removedBannersLanguagesNotPresentInDataverse(List<DataverseBannerDto> dataList) {
`removed` -> `remove`
use verb instead of adjective for method names

2019-04-25 11:48 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/bannersandmessages/messages/LazyDataverseTextMessage.java
> +    private List<DataverseTextMessageDto> removedMessageLanguagesNotPresentInDataverse(List<DataverseTextMessageDto> dataList) {
as above

2019-04-25 12:28 UTC, madryk approved these changes

2019-04-25 12:29 UTC, merged