Closes #1077: Persisting workflow execution for audit & resume after pausing
CeON/fairchive pull request #1097
Opened 2020-06-04 14:28 UTC by kaczynskid

2020-06-09 17:24 UTC, kaczynskid commented
See also https://github.com/CeON/mxrdr-extension/pull/21

2020-06-10 16:49 UTC, MrK191 requested changes

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecution.java
> +        if (steps == null) {
Will it ever be null? List is created on the field.

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionArtifact.java
> +    // FIXME: implement next
Hmm I don't think we should leave comments or class like that. It is similar to 2,4k TODO's, they don't really work :P. I think issue on github is enough.

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionStep.java
> +    @Column(name = "provider_id")
I wonder if it wouldn't be weird changing the naming scheme now, since we already have >100 tables without underscore.

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/main/resources/db/migration/V28__addWorkflowExecution.sql
> +create table workflow_execution
We don't want any constraints on the fields? Like some fields shouldn't be null?

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionRepositoryTest.java
> +    Dataset dataset;
Shouldn't it be private?

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionTest.java
> +    long datasetId = 1L;
Shouldn't all those fields be private?

2020-06-10 16:49 UTC, MrK191 commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/workflow/WorkflowContext.java
> +    WorkflowExecution asExecutionOf(Workflow workflow) {
"isExecutionOf"?

2020-06-10 16:49 UTC, MrK191 commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionRepositoryIT.java
> +    Dataset dataset;
Shouldn't fields be private?

2020-06-14 19:15 UTC, kaczynskid commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionRepositoryTest.java
> +    Dataset dataset;
no, it's a test, it's irrelevant here, only produces reading noise

2020-06-14 19:17 UTC, kaczynskid commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionTest.java
> +    long datasetId = 1L;
no, see above

2020-06-14 19:17 UTC, kaczynskid commented on dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionRepositoryIT.java
> +    Dataset dataset;
no, see above

2020-06-14 19:19 UTC, kaczynskid commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/workflow/WorkflowContext.java
> +    WorkflowExecution asExecutionOf(Workflow workflow) {
no, it does not return `boolean`, it converts a `WorkflowContext` _as_ instance of `WorkflowExecution`

2020-06-14 19:21 UTC, kaczynskid commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecution.java
> +        if (steps == null) {
It shouldn't, though I'm not entirely sure about EclipseLink messing it up...

2020-06-14 19:34 UTC, kaczynskid commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/workflow/WorkflowExecutionStep.java
> +    @Column(name = "provider_id")
I' not sure if I really notice a convention, as some table names have underscores and also some column names also, and constraint names too. Sure, a lot of them don't and are a struggle to read. What I also noticed was that names seem to be case insensitive, so in this case, for the sake of readability, the underscore version seems a better choice to me.

2020-06-15 08:33 UTC, MrK191 approved these changes

2020-06-15 12:02 UTC, merged