Closes #1233: Metadata block options
CeON/fairchive pull request #1243
Opened 2020-08-04 13:27 UTC by tomaszblazejczyk

Also fixed refreshing opened metadata fields options when metadata block checked/unchecked

2020-08-06 11:06 UTC, madryk commented
Now when we have selected option to inherit metadata blocks from parent dataverse and then
expand metadata fields - we can switch all options (required/optional and turn on turn off) they should be blocked in such situatiions like before.
![Zrzut ekranu z 2020-08-06 13-00-55](https://user-images.githubusercontent.com/8190961/89524907-a8575600-d7e5-11ea-95bd-93c765537933.png)

2020-08-06 11:07 UTC, madryk requested changes
There is a problem with inheritance mentioned in comment

2020-08-06 13:38 UTC, tomaszblazejczyk commented
This strange behavior affects only "citation" block - additional checking for "disabled" property fixed the issue

2020-08-07 09:11 UTC, madryk approved these changes

2020-08-07 12:00 UTC, merged