Closes #1381, #1382: mail domain groups
CeON/fairchive pull request #1418
Opened 2021-02-08 12:02 UTC by wtr-icm

2021-02-08 15:04 UTC, madryk requested changes

2021-02-08 15:04 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/MailDomainGroup.java
> +        @NamedQuery(name = "MailDomainGroup.findAll", query = "SELECT m FROM MailDomainGroup m")
Do we need or use anywhere this named query?

2021-02-08 15:04 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/MailDomainGroupRepository.java
> +    public List<MailDomainGroup> findAll() {
findAll is defined in parent repository - probably we don't need extra method for that.

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/ApiErrorDTO.java
> +public class ApiErrorDTO {
You could use `ApiErrorResponse` class instead - then we would have more consistency and control on how we want to present error messages

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/MailDomainGroupDTO.java
> +//        @NotBlank(message = "Domain must not be blank")
leftover comment?

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/confirmemail/ConfirmEmailServiceBean.java
> +        boolean hasNoStaleVerificationTokens = findSingleConfirmEmailDataByUser(user) == null;
It's quite weird that we check for email verification token. And not only if it was confirmed or not. Is this was taken from original dataverse source code?

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/groups/impl/mail/MailDomainGroupProvider.java
> +        return Collections.emptySet();
Not sure if we can just tell that `RoleAssignee` doesn't have any mail domain group assigned. This could make some functionality for such users not working. 
For example - code that will use this:
`public boolean checkEditDatasetLock(Dataset dataset, DataverseRequest dataverseRequest, Command command) throws IllegalCommandException {` in PermissionServiceBean - maybe it could result in user not allowed to edit for example metadata if it would rely on permissions from email group
`public void checkDownloadFileLock(Dataset dataset, DataverseRequest dataverseRequest, Command command) throws IllegalCommandException {` in PermissionServiceBean
There are quite a lot of sword endpoints that will use this method.
Some code in adding / replacing files via api also relies on that.

2021-02-08 15:04 UTC, madryk commented on dataverse-persistence/src/main/resources/db/migration/V37__addMailDomainsEntities.sql
> +    domain VARCHAR(255),
domain can be null?

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MailGroups.java
> +                    .orElseGet(() -> createErrorResponse(Response.Status.INTERNAL_SERVER_ERROR, "UnknownError"));
Maybe `.orElseThrow(ee)` would be less work for us to be more consistent with the rest of the api? (Consistent message, status, maybe incidentId creation)

2021-02-08 15:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MailGroups.java
> +                ? Response.status(Response.Status.OK).entity(groupConverter.toDTO(found.get())).build()
In most cases we use some envelope for responses. See:
```
    protected Response ok(JsonObjectBuilder bld) {
        return Response.ok(Json.createObjectBuilder()
                                   .add("status", STATUS_OK)
                                   .add("data", bld).build())
                .type(MediaType.APPLICATION_JSON)
                .build();
    }
``` 
in AbstractApiBean.

Maybe we should to something similar here and in other enpoints in this class?

2021-02-08 15:04 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/MailDomainItem.java
> +    public String getDomain() {
Maybe some comment describing what we store here? Especially info about the difference between domain with dot as first character vs no dot would be helpful

2021-02-09 11:13 UTC, wtr-icm commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/MailDomainGroupRepository.java
> +    public List<MailDomainGroup> findAll() {
I've overlooked that.

2021-02-09 13:56 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/confirmemail/ConfirmEmailServiceBean.java
> +        boolean hasNoStaleVerificationTokens = findSingleConfirmEmailDataByUser(user) == null;
NOTE: After discussion we decided to leave it as is for now.

2021-02-09 15:06 UTC, madryk approved these changes

2021-02-09 15:21 UTC, merged