Closes #1540: Fixed featuring dataverse by dataverse linking it
CeON/fairchive pull request #1566
Opened 2021-04-28 11:43 UTC by dbojanek

I hope i understood business logic behind it correctly..
Also fixed a small spelling mistake

2021-04-28 12:05 UTC, madryk requested changes

2021-04-28 12:05 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java
> -        featurableDataverses.addAll(linkingService.findLinkingDataverses(dataverseId));
I don't think that it is exactly what we want to achieve.
Let's say we have situation:
Dataverse A is linked to Dataverse B (that means that search results of B will include A)
When selecting dataverses that can be featured we want:
For Dataverse A: empty list
For Dataverse B: A
When we will apply these change then:
For Dataverse A: empty
For Dataverse B: empty
Maybe `linkingService.findLinkedDataverses` is what we want instead of `linkingService.findLinkingDataverses`?

2021-04-28 12:05 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java
> -        featurableDataverses.addAll(linkingService.findLinkingDataverses(dataverseId));
I know - it's confusing

2021-04-28 12:21 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java
> -        featurableDataverses.addAll(linkingService.findLinkingDataverses(dataverseId));
Are you sure if that's what we want? Prior to this change we would have empty list for Dataverse A in your scenario. 
Just asking if we are not overdoing this.

2021-04-29 08:00 UTC, madryk approved these changes

2021-04-29 08:07 UTC, merged