Closes #1625: Fixed order change while dis/enabling guestbooks + some refactor
CeON/fairchive pull request #1652
Opened 2021-05-24 13:00 UTC by dbojanek

I added some refactor to make page less dynamic. Making full data reload on disabling/enabling guestbook and on deselecting guestbooks from root seemed unnecessary. 
Too many db calls were made and I don't think that the purpose of this page requires that fresh data to be handled each time user performs some operation on it.

2021-05-24 15:01 UTC, madryk requested changes

2021-05-24 15:01 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java
> +        dataverse = dvService.find(dataverseId);
Why we obtain dataverse for the second time? We already did it in this method.

2021-05-24 15:01 UTC, madryk commented on dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml
> -                                                   rendered="#{manageGuestbooksPage.dataverse.id eq guestbook.dataverse.id and !guestbook.enabled}"
`manageGuestbooksPage.dataverse.id eq guestbook.dataverse.id` part of rendered was causing that button wasn't rendered in case guestbook was defined in parent dataverse. Now admin of child dataverse will be able to turn on/off guestbooks in parent dataverse

2021-05-24 15:01 UTC, madryk commented on dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml
> +                                <div class="btn-group" role="group">
This change in hierarchy of buttons is causing different rendering than before.

2021-05-25 06:54 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java
> +        dataverse = dvService.find(dataverseId);
A remnant from `refreshGuestbooks` method.

2021-05-25 06:55 UTC, dbojanek commented on dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml
> -                                                   rendered="#{manageGuestbooksPage.dataverse.id eq guestbook.dataverse.id and !guestbook.enabled}"
Yeah, my bad. I didn't realize you should not be able to turn inherited guestbook on/off..

2021-05-25 08:13 UTC, madryk approved these changes

2021-05-25 08:18 UTC, merged