Closes #1828: Handle & < > in Dataset title
CeON/fairchive pull request #1836
Opened 2021-07-23 15:03 UTC by dbojanek

2021-07-26 10:34 UTC, MrK191 requested changes

2021-07-26 10:34 UTC, MrK191 commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetVersion.java
> +        return Jsoup.parse(getTitle()).text();
Is our title embeded in html characters that we need to unencode it? Is disabling escape in xhtml not sufficient?

2021-07-27 11:01 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetVersion.java
> +        return Jsoup.parse(getTitle()).text();
Since we want to allow users to insert < > signs in title, we must take care of possible js <script> injections. 
We want to, whenever we display title in html to have it escaped, but we also use title in many more places (page titles, exported data, ...). In all of those places we must take care of possible html tags the same way we do in html, to deliver the same data to users.

2021-07-27 13:20 UTC, MrK191 approved these changes

2021-07-27 13:40 UTC, merged