Closes #1877 #1878: Lazy data model on dashboard-users.xhtml
CeON/fairchive pull request #1890
Opened 2021-08-17 14:50 UTC by dbojanek

2021-08-18 14:32 UTC, madryk requested changes

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-users.xhtml
> +                                 selectionMode="single"
I don't think that `selection="#{DashboardUsersPage.selectedUserInfo}"` and `selectionMode="single"` is used in any way. We manage selectedUserInfo by ourselves.

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-users.xhtml
> +                                 styleClass="largePopUp disable-scroll"
I'm not sure why we added those classes? They seem to be used only in `dialog` context

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-users.xhtml
> +                                                         onkeypress="if (event.keyCode == 13) { $('#dashboardUsersForm\\:userInfoTable\\:searchButton').click(); return false; }"
it is possible to add `widgetVar` on search button. That way we could do `PF('searchButton').getJQ().click()` to have the same results (we don't have to play with escaping selector, and id hierarchy)

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-users.xhtml
> +                                                       onclick="$('#dashboardUsersForm\\:userInfoTable\\:globalFilter\\:filter'); PF('userInfoTable').filter();"
`$('#dashboardUsersForm\\:userInfoTable\\:globalFilter\\:filter');` - this is some leftover? I don't think that it does anything.

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-users.xhtml
> +                            <div jsf:id="filesHeaderBlock" class="row" jsf:rendered="#{true}">
`jsf:rendered="#{true}"` unnecessary code

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/LazyUsersInfoDataModel.java
> +        return filterValue;
IMO:
```
return Objects.toString(filterMeta.get("globalFilter").getFilterValue(), StringUtils.EMPTY)
```
would be a little easier to comprehend what actually we have in mind. We could also make a constant for "globalFilter" string - maybe in `PrimefacesUtils` (couldn't find more appropriate class right now). Unfortunetly only in newer version of primefaces (v10) there is a constant for that in `FilterMeta.GLOBAL_FILTER_KEY`.

Also we could rename method to `getGlobalFilterValue` to further explain what is going on.

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        qstr += " prov.id, prov.factoryalias";
prov.factoryalias is not used anywhere. We could remove it from here and also associated transient field on authenticateduser entity.

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        qstr += " WHERE";
If we remove factoryalias then fetching authenticationproviderrow is obsolete. (We can obtain prov.id from prov_lookup.authenticationproviderid)

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    public UserRepository(Class<AuthenticatedUser> entityClass) {
Do we need this constructor?

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +
Rename to AuthenticatedUserRepository? Imo we should stick to convention that repository should have full entity name.

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        }
I think that this is not safe. I think that it is fragile to sql injection.

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +                .setMaxResults(resultLimit)
Defining LIMIT and OFFSET in query and then manipulating `setFirstResult` and `setMaxResults` is kind of pointless

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    }
If we assign above then there is really no point of having native query. We could make normal query using criteriabuilder api - it would have same effect, but we wouldn't have to map entities ourselves.
`findSearchedAuthenticatedUsers` could look something like this:
```
    public List<AuthenticatedUser> findSearchedAuthenticatedUsers(String sortKey, int resultLimit, int offset, String searchTerm, boolean isSortAscending) {
        CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();

        CriteriaQuery<AuthenticatedUser> query = criteriaBuilder.createQuery(AuthenticatedUser.class);
        Root<AuthenticatedUser> root = query.from(AuthenticatedUser.class);
        root.fetch("authenticatedUserLookup");

        query.select(root)
            .where(getSearchPredicates(searchTerm, root, criteriaBuilder))
            .orderBy(isSortAscending ? criteriaBuilder.asc(root.get(sortKey)) : criteriaBuilder.desc(root.get(sortKey)));

        return em.createQuery(query)
                .setFirstResult(offset)
                .setMaxResults(resultLimit)
                .getResultList();
    }

    private Predicate[] getSearchPredicates(String searchTerm, Root<AuthenticatedUser> root, CriteriaBuilder criteriaBuilder) {
        if (searchTerm.isEmpty()) {
            return new Predicate[] {};
        }
        List<Predicate> predicates = new ArrayList<>();
        predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("userIdentifier")), searchTerm.toLowerCase()+"%"));
        predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("firstName")), searchTerm.toLowerCase()+"%"));
        predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("lastName")), searchTerm.toLowerCase()+"%"));
        predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("email")), searchTerm.toLowerCase()+"%"));
        return new Predicate[] {criteriaBuilder.or(predicates.toArray(new Predicate[]{})) };
    }
```
and count query will be:
```
    public Long countSearchedAuthenticatedUsers(String searchTerm) {
        CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();

        CriteriaQuery<Long> query = criteriaBuilder.createQuery(Long.class);
        Root<AuthenticatedUser> root = query.from(AuthenticatedUser.class);
        
        query.select(criteriaBuilder.count(query.from(AuthenticatedUser.class)))
            .where(getSearchPredicates(searchTerm, root, criteriaBuilder));

        return em.createQuery(query).getSingleResult();
    }
```
The slight difference would be in sortKey: instead of for example "u.id" we would have to pass "id" - name of the property in `AuthenticatedUser` class

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    public List<Object[]> findSearchedAuthenticatedUsers(String sortKey, int resultLimit, int offset, String searchTerm, boolean isSortAscending) {
I would advise to make sortKey some kind of enum so we would have more control over what can be passed here.

2021-08-18 14:32 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +
Maybe we could add some integration test for that class?

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardUsersService.java
> +    public AuthenticatedUser changeSuperuserStatus(Long userId) {
Just change method above to `changeSuperuserStatus(Long userId)` as we already making `userServiceBean.find(user.getId());` there

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardUsersService.java
> +        return commandEngine.submit(new RevokeAllRolesCommand(dbUser, dvRequestService.getDataverseRequest()));
```
public AuthenticatedUser revokeAllRolesForUser(Long userId) {
    return revokeAllRolesForUser(userServiceBean.find(userId));
}
```
?
Or we could also get rid of `revokeAllRolesForUser(AuthenticatedUser user)` as it is used only in tests

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/LazyUsersInfoDataModel.java
> +        this.setRowCount(userService.getUserCount(filterValue).intValue());
I think that userListResults already comes with total user count. So we can obtain it from there - without extra query

2021-08-18 14:32 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/LazyUsersInfoDataModel.java
> +        return userListMaker.runUserSearch(searchTerm, usersPerPage, selectedPageNumber, sortColumn, isSortAscending);
Can we make a little cleanup in `UserListMaker` and related classes?:
```
diff --git a/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListMaker.java b/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListMaker.java
index 6543444aa..4da0f3e36 100644
--- a/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListMaker.java
+++ b/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListMaker.java
@@ -1,8 +1,3 @@
-/*
- * To change this license header, choose License Headers in Project Properties.
- * To change this template file, choose Tools | Templates
- * and open the template in the editor.
- */
 package edu.harvard.iq.dataverse.userdata;
 
 import edu.harvard.iq.dataverse.UserServiceBean;
@@ -10,23 +5,17 @@ import edu.harvard.iq.dataverse.mydata.Pager;
 import edu.harvard.iq.dataverse.persistence.user.AuthenticatedUser;
 
 import java.util.List;
-import java.util.logging.Logger;
 
 /**
  * @author rmp553
  */
 public class UserListMaker {
 
-    private static final Logger logger = Logger.getLogger(UserListMaker.class.getName());
-
-    UserServiceBean userService;
-
-    public boolean errorFound = false;
-    public String errorMessage = null;
+    private UserServiceBean userService;
 
-    public static final int ITEMS_PER_PAGE = 25;
-    public static final int MIN_ITEMS_PER_PAGE = 1;
-    public static final int DEFAULT_OFFSET = 0;
+    private static final int ITEMS_PER_PAGE = 25;
+    private static final int MIN_ITEMS_PER_PAGE = 1;
+    private static final int DEFAULT_OFFSET = 0;
 
 
     /*
@@ -36,35 +25,6 @@ public class UserListMaker {
         this.userService = userService;
     }
 
-
-    public Long getTotalUserCount(boolean superusers_only) {
-
-        if (superusers_only) {
-            return userService.getSuperUserCount();
-        } else {
-            return userService.getUserCount(null);  // send null for the optional search term
-        }
-
-    }
-
-
-    /**
-     * Get user count with search
-     *
-     * @param searchTerm
-     * @return
-     */
-    public Long getUserCountWithSearch(String searchTerm) {
-
-        if (searchTerm == null) {
-            searchTerm = "";
-        } else {
-            searchTerm = searchTerm.trim();
-        }
-
-        return userService.getUserCount(searchTerm);
-    }
-
     public UserListResult runUserSearch(String searchTerm, Integer itemsPerPage, Integer selectedPage, String sortKey, boolean isSortAscending) {
 
         // Initialize searchTerm
@@ -89,12 +49,6 @@ public class UserListMaker {
         // -------------------------------------------------
         Long userCount = userService.getUserCount(searchTerm);
 
-        // Are there any hits?  No; return info
-        if ((userCount == null) || (userCount == 0)) {
-            pager = new Pager(0, itemsPerPage, selectedPage);
-            return new UserListResult(searchTerm, pager, null);
-        }
-
         // -------------------------------------------------
         // (2) Do some calculations here regarding the selected page, offset, etc.
         // -------------------------------------------------
@@ -107,63 +61,23 @@ public class UserListMaker {
         // (3) Retrieve the users
         // -------------------------------------------------
         List<AuthenticatedUser> userList = userService.getAuthenticatedUserList(searchTerm, sortKey, isSortAscending, itemsPerPage, offset);
-        if (userList == null) {
-            pager = new Pager(0, itemsPerPage, selectedPage);
-            return new UserListResult(searchTerm, pager, null);
-        }
 
         pager = new Pager(userCount.intValue(), itemsPerPage, selectedPage);
 
-        return new UserListResult(searchTerm, pager, userList);
+        return new UserListResult(pager, userList);
 
     }
 
 
-    public OffsetPageValues getOffset(Long userCount, Integer selectedPage, Integer itemsPerPage) {
-
-        if (userCount == null) {
-            return new OffsetPageValues(DEFAULT_OFFSET, 0);
-        }
-
-        if (itemsPerPage == null) {
-            itemsPerPage = ITEMS_PER_PAGE;
-        }
-        if ((selectedPage == null) || (selectedPage < 1)) {
-            selectedPage = 1;
-        }
+    private OffsetPageValues getOffset(Long userCount, Integer selectedPage, Integer itemsPerPage) {
 
         int offset = (selectedPage - 1) * itemsPerPage;
         if (offset > userCount) {
-            offset = DEFAULT_OFFSET;
-            selectedPage = 1;
+            return new OffsetPageValues(DEFAULT_OFFSET, 1);
         }
 
         return new OffsetPageValues(offset, selectedPage);
 
     }
 
-
-    public boolean hasError() {
-        return this.errorFound;
-    }
-
-    public String getErrorMessage() {
-        return this.errorMessage;
-    }
-
-    private void addErrorMessage(String errMsg) {
-        this.errorFound = true;
-        this.errorMessage = errMsg;
-    }
-
-    private void msg(String s) {
-        System.out.println(s);
-    }
-
-    private void msgt(String s) {
-        msg("-------------------------------");
-        msg(s);
-        msg("-------------------------------");
-    }
-
 }
```
and
```
diff --git a/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListResult.java b/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListResult.java
index 0731a555b..134324487 100644
--- a/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListResult.java
+++ b/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/userdata/UserListResult.java
@@ -22,88 +22,13 @@ public class UserListResult {
 
     private static final Logger logger = Logger.getLogger(UserListResult.class.getName());
 
-    private String searchTerm;
-
     private Pager pager;
-    private List<AuthenticatedUser> userList;
-
-    private boolean success;
-
-    private String errorMessage;
-
-
-    public UserListResult(String searchTerm, Pager pager, List<AuthenticatedUser> userList) {
 
+    private List<AuthenticatedUser> userList;
 
-        if (searchTerm == null) {
-            searchTerm = "";
-        }
-        this.searchTerm = searchTerm;
 
+    public UserListResult(Pager pager, List<AuthenticatedUser> userList) {
         this.pager = pager;
-        if (this.pager == null) {
-            logger.severe("Pager should never be null!");
-        }
-
-        this.userList = userList;
-        if (this.userList == null) {
-            this.userList = new ArrayList<>();  // new empty list
-        }
-
-    }
-
-    public Integer getSelectedPageNumber() {
-
-        if (pager == null) {
-            return 1;
-        }
-        return pager.getSelectedPageNumber();
-    }
-
-    /**
-     * Set searchTerm
-     *
-     * @param searchTerm
-     */
-    public void setSearchTerm(String searchTerm) {
-        this.searchTerm = searchTerm;
-    }
-
-    /**
-     * Get for searchTerm
-     *
-     * @return String
-     */
-    public String getSearchTerm() {
-        return this.searchTerm;
-    }
-
-
-    /**
-     * Set pager
-     *
-     * @param pager
-     */
-    public void setPager(Pager pager) {
-        this.pager = pager;
-    }
-
-    /**
-     * Get for pager
-     *
-     * @return Pager
-     */
-    public Pager getPager() {
-        return this.pager;
-    }
-
-
-    /**
-     * Set userList
-     *
-     * @param userList
-     */
-    public void setUserList(List<AuthenticatedUser> userList) {
         this.userList = userList;
     }
 
@@ -116,45 +41,6 @@ public class UserListResult {
         return this.userList;
     }
 
-
-    /**
-     * Set success
-     *
-     * @param success
-     */
-    public void setSuccess(boolean success) {
-        this.success = success;
-    }
-
-    /**
-     * Get for success
-     *
-     * @return boolean
-     */
-    public boolean getSuccess() {
-        return this.success;
-    }
-
-
-    /**
-     * Set errorMessage
-     *
-     * @param errorMessage
-   [...]

2021-08-20 08:17 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        qstr += " prov.id, prov.factoryalias";
We are using it to build json for `Admin.filterAuthenticatedUsers`. I'm not sure if we want to get rid of it like that.

2021-08-20 08:57 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        qstr += " prov.id, prov.factoryalias";
It's being used in admin endpoint. I've moved `AuthenticationProvider.getFriendlyName` to `AuthenticatedUserUtil.getAuthenticationProviderFriendlyName` so I can drop transient field from authenticateduser entity.

2021-08-20 09:02 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    public UserRepository(Class<AuthenticatedUser> entityClass) {
Probably not - auto generated.

2021-08-20 09:09 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        }
For some reason `.setParameter` was not working here. I'll take another look.

2021-08-20 09:45 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +        }
Ok, native queries don't support named parameters.. I've changed it to use positional parameter.

2021-08-20 09:56 UTC, dbojanek commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    }
I was under an impression that we are being discouraged from using CriteriaBuilder.. (not that I'm familiar with it).

2021-08-20 10:29 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserRepository.java
> +    }
If we could write something in jpql then probably we should write it using jpql. CriteriaBuilder api is quite unelegant and can get out of hand. But still I think it is better than native + mapping quite complex object by hand. In this case there is one thing that stops us from using jpql - that is sorting that comes from parameters. If we want to use jpql in such case we would have to add it query using string concatenation (`"select ... order by " + sortClause`). But we would have to ensure that param `sortKey` is correct (there will be no checking of sql injection issues, etc.).

2021-08-20 11:14 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardUsersService.java
> +    public AuthenticatedUser changeSuperuserStatus(Long userId) {
Forgot to remove that one.

2021-08-20 11:16 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardUsersService.java
> +        return commandEngine.submit(new RevokeAllRolesCommand(dbUser, dvRequestService.getDataverseRequest()));
Also forgot to remove that one.

2021-08-20 11:22 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/LazyUsersInfoDataModel.java
> +        this.setRowCount(userService.getUserCount(filterValue).intValue());
Well I don't think it does. Maybe I'm missing something?

2021-08-20 11:47 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/LazyUsersInfoDataModel.java
> +        this.setRowCount(userService.getUserCount(filterValue).intValue());
`userListResults.getPager().getNumResults()`

2021-08-20 15:52 UTC, madryk approved these changes

2021-08-20 17:26 UTC, merged