Closes #1879: remove temporary files
CeON/fairchive pull request #1895
Opened 2021-08-18 13:50 UTC by dbojanek

2021-08-18 18:04 UTC, madryk requested changes

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/sav/SAVFileReader.java
> +    private void cleanUp() {
I don't think that this has any effect? `SavFileReader` is created using `new` so it is not a part of any context (either ejb nor cdi).
```
        } else if (mimeType.equals(ApplicationMimeType.SPSS_SAV.getMimeValue())) {
            ingestPlugin = new SAVFileReader(new SAVFileReaderSpi());
```

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataaccess/ImageThumbConverter.java
> +                sourcePdfFile.ifPresent(File::delete);
Didn't we already removed that file using previous solution? Notice that now `tempPdfFile == sourcePdfFile` if we have remote storage and if we have file storage tempPdfFile is empty and sourcePdfFile is not.

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/DDIExportServiceBean.java
> +            if (storageIO != null && storageIO.isRemoteFile()) {
Similar case as some comment above. Did we have problems with deleting temporary file before this change?

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java
> +            firstPassTempFile.delete();
I don't think that will solve the issue completely. We are removing file only if we get to so-called second-pass, file is created before first pass. Unfortunately I can't think of "pretty" solution that would not be a complete rewrite of the class. 
Maybe we could move the creation of firstPassTempFile to the method above and pass it to this method.

```
File firstPassTempFile = File.createTempFile("firstpass-", ".csv");
try {
   int lineCount = readFile(localBufferedReader, dataTable, tabFileWriter, firstPassTempFile);
finally {
  firstPassTempFile.delete();
}
```

I know that the solution is not pretty but I can't think of a better way right now.

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java
> +            finalWriter.close();
finalWriter could be easily included in try with resources statement

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java
> +            firstPassTempFile.delete();
Same issue as in CsvFileReader.

2021-08-18 18:04 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
> +                    tabFile.delete();
A little better. But still quite possible for leaving some leftovers. Before the creation of this file and this delete statement there are quite few try catch blocks with return statements. Maybe lets leave it for now. As I think that when resolving issue with failure on bigger tabular files this method could be changed a little and deletion of file maybe will be a little easier.

2021-08-19 08:12 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/DDIExportServiceBean.java
> +            if (storageIO != null && storageIO.isRemoteFile()) {
I wasn't sure. I've tried to follow usage of `StorageIOUtils.obtainAsLocalFile`.

2021-08-19 11:04 UTC, madryk approved these changes

2021-08-19 11:10 UTC, merged