Closes #1887: Fix ingest
CeON/fairchive pull request #1902
Opened 2021-08-23 08:46 UTC by wtr-icm

2021-08-23 12:09 UTC, madryk requested changes

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
> +        if (tabDataIngest == null) {
This is always false `if`. `tabDataIngest = ingestPlugin.read(inputStream, additionalData);` will either throw exception or will return value. We could safely remove this `if.

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
> +                        ? TextMimeType.CSV.getMimeValue() : originalContentType);
I think that this conditional is always false `TextMimeType.CSV_ALT.getMimeValue().equals(dataFile.getContentType())`. Above we have `dataFile.setContentType(TextMimeType.TSV_ALT.getMimeValue());` statement.

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java
> +                logger.warning("Failed to save the ingested original! " + iox.getMessage());
We most probably want to remove this catch. If original file failed to save then next line `tabularStorageIO.savePath` could potentially overwrite the original file (as a result we would end up without the file that was stored originally by the user).

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java
> +            dataFile.setFilesize(tabularStorageIO.getSize());
Probably we could remove this `setFilesize` (setFilesize was already done in IngestServiceBean).

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java
> +            tabFile.delete();
Probably it would be better if we would do this delete outside this method:
try {
  return finalizeIngestService.finalizeIngest(dataFile, additionalData, tabDataIngest, tabFile);
} finally {
  tabFile.delete();
}

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java
> +            }
Maybe `return false` would be a good option here? Just a proposition - it doesn't have any critical meaning. It only will change one logger statement in `IngestMessageBean` (`logger.warning("Error occurred during ingest job for file id " + datafile_id + "!");`)

2021-08-23 12:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
> +        if (!postIngestTasksSuccessful) {
This `if` will be true only in case when:
```
        try {
            produceSummaryStatistics(dataFile, tabFile);
            produceFrequencyStatistics(dataFile, tabFile);
```
will throw an exception. I would propose to get rid of this boolean and just return false in catch statement

2021-08-24 07:11 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java
> +            dataFile.setFilesize(tabularStorageIO.getSize());
It's not very clear why they're setting that size again, but indeed it seems redundant.
This also means that following `save(dataFile)` is not needed.

2021-08-24 09:00 UTC, madryk approved these changes

2021-08-24 09:07 UTC, merged