Closes #2022: Rewrite DatasetField validators
CeON/fairchive pull request #2027
Opened 2021-10-14 08:52 UTC by wtr-icm

2021-10-18 08:28 UTC, madryk requested changes

2021-10-18 08:28 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/FileService.java
> +            validationResults.forEach(r -> logger.warn(r.getMessage()));
I'm pretty positive that in some cases that doesn't have to do nothing with metadata validation (like for example this file deletion) was executed just to prevent `ConstraintValidationException` which in turn would prevent from saving changes in database. Such cases was not theoretical because definition of fields could change in time (modification of dataset fields schema or even making field required by modifying a dataverse). My theory is that it was done because default feedback from `ConstraintViolationException` message is not really helpful. Since we are moving away from JPA constraint then probably such checks could be omitted? Maybe it is an idea for additional task where we could make some cleanup regarding this issue?

2021-10-18 08:28 UTC, madryk commented on dataverse-persistence/src/main/resources/db/migration/V57__addValidation.sql
> +WHERE name='grantNumberAgencyIdentifier';
Since we already writing a migration we could remove `validationFormat` from `DatasetFieldType`

2021-10-18 08:28 UTC, madryk commented on scripts/api/data/metadatablocks/citation.tsv
> +	title	Title	Full title by which the Dataset is known.	Enter title...	text	0		TRUE	FALSE	FALSE	FALSE	TRUE	TRUE		TEXT	"{""buttonActionHandler"":""AddReplicationTextActionHandler"",""buttonActionTextKe
What about the rest of metadata blocks? It for sure, some method for obtaining tsv from database would be helpful in such cases like this. What do you think? Maybe we should create a task for that and then modify the rest of tsv's?

2021-10-18 08:28 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetField.java
>          return this.getDatasetFieldType().getDisplayOrder();
I couldn't found the removal of `@ValidateDatasetFieldType` and the rest. Do we plan on keeping both: java and jpa validation?

2021-10-18 08:28 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/datasetfield/validators/StandardFieldValidatorBase.java
> +        }
Hmm... I think we should move this to the class that executes validation for fields (`FieldValidationDispatcher`). Now I think that we not understood ourselves when I told that IMO we should keep validation in one place. I thought that you will want to keep something inside `JPA's Constraints`. But now I think what you meant is exactly what I am suggesting right now. Is this correct?

2021-10-18 08:28 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
>                      }
I would try to rewrite the whole thing as follows:
```
DatasetVersion versionToValidate = ds.getVersions().get(0);
List<ValidationResult> validationResults = fieldValidationService.validateFieldsOfDatasetVersion(versionToValidate);

if (!validationResults.isEmpty()) {

if (settingsService.isTrueForKey(SettingsServiceBean.Key.ScrubMigrationData)) {
  validationResults.forEach(r -> processMigrationValidationError(r.getField(), cleanupLog, metadataFile.getName()));

  validationResults = fieldValidationService.validateFieldsOfDatasetVersion(versionToValidate);
  validationResults.forEach(r -> cleanupLog.println(String.format("Data modified - File: %s; Field: %s; Invalid value:  '%s' Converted Value:'%s'", metadataFile.getName(), field.getDatasetFieldType().getDisplayName(), field.getValue(), DatasetField.NA_VALUE)));
  validationResults.forEach(r -> r.getField().setFieldValue(DatasetField.NA_VALUE));
} else {
  validationResults.forEach(r -> r.getField().setFieldValue(DatasetField.NA_VALUE));
}

}
    
```
If we are making an assumption that one validation can depend one other field value then checking only values of fields that had failed to validate in the first run is not so accurate (`ScrubMigrationData` case).
That's why I would try to get rid of field by field validation and just run it on the all fields.

2021-10-18 08:28 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
> +                            throw new ImportException(message);
Similar case as above

2021-10-27 08:53 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/FileService.java
> +            validationResults.forEach(r -> logger.warn(r.getMessage()));
:arrow_right: new Task 1

2021-10-27 08:54 UTC, wtr-icm commented on dataverse-persistence/src/main/resources/db/migration/V57__addValidation.sql
> +WHERE name='grantNumberAgencyIdentifier';
:arrow_right: new Task 1

2021-10-27 08:54 UTC, wtr-icm commented on scripts/api/data/metadatablocks/citation.tsv
> +	title	Title	Full title by which the Dataset is known.	Enter title...	text	0		TRUE	FALSE	FALSE	FALSE	TRUE	TRUE		TEXT	"{""buttonActionHandler"":""AddReplicationTextActionHandler"",""buttonActionTextKe
:arrow_right: new Task 2

2021-10-27 08:54 UTC, wtr-icm commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetField.java
>          return this.getDatasetFieldType().getDisplayOrder();
:arrow_right: new Task 1

2021-10-27 08:55 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
>                      }
Fixed in the way we discussed it yesterday.

2021-10-27 14:15 UTC, madryk approved these changes

2021-10-29 10:37 UTC, merged