Closes #2049: Fix search results incorrectly marked as linked
CeON/fairchive pull request #2061
Opened 2021-11-08 09:45 UTC by wtr-icm

2021-11-08 14:56 UTC, madryk requested changes

2021-11-08 14:56 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
> +        }
Keeping `Optional<String> filterDownToSubtree` variable is kind of pointless now. Just making:
```
if (!dataverse.isRoot()) {
  dataversePath = dataverseDao.determineDataversePath(dataverse);
  filterQueriesFinal.add(SearchFields.SUBTREE + ":\"" + dataversePath + "\"");
}
```
is a little simpler

2021-11-09 07:15 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
> +        }
Yes, but unfortunately `filterDownToSubtree` is also used later in the code:
```
        if (filterDownToSubtree.isPresent()) {
            this.responseFilterQueries = solrQueryResponse.getFilterQueries().stream()
                    .filter(filter -> !filterDownToSubtree.get().equals(filter.getQuery()))
                    .collect(toList());
        } else {
            this.responseFilterQueries = solrQueryResponse.getFilterQueries();
        }
```
so I think we cannot remove it altogether.

2021-11-09 08:07 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
> +        }
Oh, sorry. I didn't notice.

2021-11-09 08:08 UTC, madryk approved these changes

2021-11-09 08:38 UTC, merged