Closes #198: OpenAire standard taken from IQSS
CeON/fairchive pull request #207
Opened 2019-07-03 14:41 UTC by dbojanek

2019-07-04 13:23 UTC, madryk requested changes

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/dataset-versions.xhtml
> +                        <h:outputText rendered="#{versionTab.released or versionTab.deaccessioned}" value="#{versionTab.versionNumber}.#{versionTab.versionMinorNumber}" /></a>
This will not render - entity `DatasetVersion` don't have `versionMinorNumber` property.

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/dataset-versions.xhtml
> +                <h:outputText rendered="#{versionTab.released or versionTab.deaccessioned}" value="#{versionTab.versionNumber}.#{versionTab.versionMinorNumber}" />
same here

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/file-versions.xhtml
> +                        <h:outputText value="#{versionTab.datasetVersion.versionNumber}.#{versionTab.datasetVersion.versionMinorNumber}" />
here too

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/file-versions.xhtml
> +                                  value="#{versionTab.datasetVersion.versionNumber}.#{versionTab.datasetVersion.versionMinorNumber}" />
here too

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/file-versions.xhtml
> +                              value="#{versionTab.datasetVersion.versionNumber}.#{versionTab.datasetVersion.versionMinorNumber}" />
here too

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/file-versions.xhtml
> +                              value="#{versionTab.datasetVersion.versionNumber}.#{versionTab.datasetVersion.versionMinorNumber}" />
here too

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/webapp/file.xhtml
> +                                                  value="#{bundle['file.DatasetVersion']} #{FilePage.fileMetadata.datasetVersion.versionNumber}.#{FilePage.fileMetadata.datasetVersion.versionMinorNumb
here too

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/CleanupTest.java
> +public class CleanupTest {
This test is in different package than `Cleanup` class. It should be in `edu.harvard.iq.dataverse.export.openaire`

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/FirstNameTest.java
> +public class FirstNameTest {
This is also in wrong package

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/FirstNameTest.java
> +public class FirstNameTest {
Also could we rename this to `FirstNamesTest` to be compliant with tested class name?

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/OpenAireExportUtilTest.java
> +public class OpenAireExportUtilTest {
wrong package

2019-07-04 13:23 UTC, madryk commented on pom.xml
> +        </dependency>
This jar is already added in dataverse-persistence/pom.xml we don't need it here

2019-07-04 13:23 UTC, madryk commented on dataverse.properties
> +DoiProvider=FAKE
Unnecessary file

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/Organizations.java
> +            "edu/harvard/iq/dataverse/firstNames/en-token.bin"
It looks like we have exact copies of `en-ner-organization.bin`, `es-ner-organization.bin` and `en-token.bin` both in `/src/java/resources` and `/src/test/resources`. Actually it looks like only those from `/src/java/resources` are needed

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/OrganizationsTest.java
> +public class OrganizationsTest {
wrong package

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/OpenAireExporterTest.java
> +public class OpenAireExporterTest {
wrong package

2019-07-04 13:23 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/FirstNames.java
> +    public static String YOB_FILENAME = "edu/harvard/iq/dataverse/firstNames/yob2017.txt";
There is no point in keeping `nam_dict.txt` and `yob2017.txt` in `src/test/resources` and `src/main/resources`

2019-07-08 10:41 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/CleanupTest.java
> +public class CleanupTest {
We should keep tests separate from non tests code:
`dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/CleanupTest.java` -> `dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/openaire/CleanupTest.java`

2019-07-08 10:41 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/FirstNamesTest.java
> +public class FirstNamesTest {
We should keep tests separate from non tests code:
`dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/FirstNamesTest.java` -> `dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/openaire/FirstNamesTest.java`

2019-07-08 10:41 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtilTest.java
> +public class OpenAireExportUtilTest {
We should keep tests separate from non tests code:
`dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtilTest.java` -> `dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtilTest.java`

2019-07-08 10:41 UTC, madryk commented on dataverse.properties
> +DoiProvider=FAKE
File is still in repo

2019-07-08 11:00 UTC, madryk requested changes

2019-07-08 11:00 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OrganizationsTest.java
> +public class OrganizationsTest {
`dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OrganizationsTest.java` -> `dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/openaire/OrganizationsTest.java`

2019-07-08 11:00 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExporterTest.java
> +public class OpenAireExporterTest {
`dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExporterTest.java` -> `dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExporterTest.java`

2019-07-08 11:00 UTC, madryk commented on dataverse-webapp/pom.xml
> +            <scope>compile</scope>
In whole project we use junit as testing framework - why we introducing another testing framework?

2019-07-08 11:00 UTC, madryk commented on dataverse-webapp/pom.xml
> +            <scope>compile</scope>
junit should stay in test scope - and is already defined in parent pom

2019-07-08 11:00 UTC, madryk commented on dataverse-webapp/pom.xml
> -            <scope>test</scope>
this library is test specific - we don't use it in non test code. Should stay in test scope

2019-07-08 11:16 UTC, dbojanek commented on dataverse-webapp/pom.xml
> +            <scope>compile</scope>
Auto-added by Intellij. Should've realized it thou.

2019-07-08 11:16 UTC, dbojanek commented on dataverse-webapp/pom.xml
> +            <scope>compile</scope>
Auto-added by Intellij. Should've realized it thou.

2019-07-08 11:59 UTC, madryk approved these changes

2019-07-08 12:03 UTC, merged