Closes #2081: Clean mydata
CeON/fairchive pull request #2085
Opened 2021-11-30 08:14 UTC by wtr-icm

2021-12-01 08:44 UTC, madryk requested changes

2021-12-01 08:44 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DataRetriever.java
> +public class DataRetriever extends AbstractApiBean {
As we moving things. Can we rename this class to something more descriptive (DataRetriever doesn't tell me a thing). Maybe to be consistent with most of the other endpoints we could just name it `MyData`?

2021-12-01 08:44 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DataRetriever.java
> +public class DataRetriever extends AbstractApiBean {
We can now modify `ApiConfiguration` so it will scan only `edu.harvard.iq.dataverse.api` package.

2021-12-01 08:44 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
> +            initMyData();
Correct me if I'm wrong but this statement doesn't make any sense. `initMyData()` will check if user is authenticted. But this is already done before in init method:
```
        if (!isUserAuthenticated()) {
            return permissionsWrapper.notAuthorized();
        }
```
If it somehow would not be the true then with other tabs we would have a problem

2021-12-01 08:44 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
> +            initMyData();
As the comment above. I don't think that this have any effect.

2021-12-02 12:17 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DataRetriever.java
> +public class DataRetriever extends AbstractApiBean {
It'll rename it in #2080

2021-12-02 14:46 UTC, madryk approved these changes

2021-12-02 14:58 UTC, merged