Closes #2080: Clean DataRetrieverAPI (now MyData)
CeON/fairchive pull request #2092
Opened 2021-12-07 10:40 UTC by wtr-icm

2021-12-10 16:09 UTC, madryk requested changes

2021-12-10 16:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MyData.java
> +                                   @QueryParam("key") String apiToken) {
`apiToken` param could be removed

2021-12-10 16:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MyData.java
> +        } catch (WrappedResponse wrappedResponse) {
We probably could omit catching `WrappedResponse` - exception ot this type is handled globally

2021-12-10 16:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MyData.java
> +            return error(Response.Status.INTERNAL_SERVER_ERROR, "Sorry! There was an error with the search service.");
Maybe we could move it to the catch statement (`catch (SearchException ex) {`)?

2021-12-10 16:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/SolrSearchResultDTO.java
> +                    result.setParentAlias(idToParentAlias.get(id));
IMO we should index this information and here just use the value from solr. Maybe we could add a separate task for it?

2021-12-10 16:09 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/PagerDTO.java
> +            if (Mode.CARD.equals(mode)) {
IMO distinction between modes adds only noise. As far as I can see `Pager` is used only in mydata and listing users (superuser only operation). Maybe we can take advantage that mydata endpoint was never documented and go with version that was used in listing users?
BTW: this whole `Pager` object is so pointless in exposing it via api - but this is a discussion for another time.

2021-12-17 19:28 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MyData.java
> +            return error(Response.Status.INTERNAL_SERVER_ERROR, "Sorry! There was an error with the search service.");
Moved. In case of null solrQueryResponse (which should most probably not happen) we'll get Internal Server Error anyway.

2021-12-17 20:21 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/SolrSearchResultDTO.java
> +                    result.setParentAlias(idToParentAlias.get(id));
I've done some changes, but I'm not sure whether I understood your comment correctly.

2021-12-18 04:14 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/SolrSearchResultDTO.java
> +                    result.setParentAlias(idToParentAlias.get(id));
Your change is ok. What I meant is that we could add an parent dataverse alias when indexing in solr. That way we could not add an extra database query to obtain it (`dataverseDao.getParentAliasesForIds`).

2021-12-18 04:15 UTC, madryk approved these changes

2021-12-18 08:41 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/SolrSearchResultDTO.java
> +                    result.setParentAlias(idToParentAlias.get(id));
Ok thanks. I think that's a good idea to make a task for this kind of improvement.

2021-12-18 08:41 UTC, merged