Closes #2116: Remove JsonPrinter (stages 1, 2, 3)
CeON/fairchive pull request #2118
Opened 2022-01-05 14:53 UTC by wtr-icm

2022-01-13 13:55 UTC, madryk requested changes

2022-01-13 13:55 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/MetadataBlocks.java
> +                .filter(Objects::nonNull)
Do we need this filter?

2022-01-13 13:55 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/AuthenticatedUserDTO.java
> +public class AuthenticatedUserDTO {
isn't it the same as `UserDTO`?

2022-01-13 13:55 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/MetadataBlockWithFieldsDTO.java
> +        getFields().removeIf(f -> TO_REMOVE.equals(f.getValue()));
IMO it should be a responsibility of DatasetFieldDTO to remove email fields in its children

2022-01-19 09:29 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/AuthenticatedUserDTO.java
> +public class AuthenticatedUserDTO {
There are some differences in properties and in their names – we can however extract a base class (but only after merging with `develop` branch as in the current PR the class `UserDTO` does not exist) and inherit it in `AuthenticatedUserDTO` and `UserDTO` (with optional unification of shared properties names), but I don't know whether we want to do that.

2022-01-24 18:22 UTC, madryk requested changes

2022-01-24 18:22 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetFieldDTOFactory.java
> +    public static final String COMPOUND = "compound";
Since we are adding constants. Can we use them in the rest of the code. I mean in this class and in `DatasetFieldDTO`. Also it would be probably better if we define this constants directly in `DatasetFieldDTO`

2022-01-24 18:22 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetFieldDTO.java
> +    private Object value;
Maybe we could add at least a comment what kind of values we are expecting here depending on the situation?

2022-01-24 18:22 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/dublincore/DublinCoreExportUtil.java
> +    public static void datasetJson2dublincore(String datasetDtoAsJson, OutputStream outputStream, String dcFlavor) throws XMLStreamException {
Didn't we get rid of versions that uses `String` or `JsonObject` as `DatasetDTO`?

2022-01-31 08:56 UTC, madryk approved these changes

2022-01-31 09:58 UTC, merged