Closes #2506: Removal of harvested DOI
CeON/fairchive pull request #2523
Opened 2024-07-19 14:01 UTC by diasf

Support for removing harvested DOI. Refactored common part with OAI harvester.

Issue: #2506

2024-09-12 08:14 UTC, madryk requested changes

2024-09-12 08:14 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/DataciteDOIHarvester.java
>      public HarvesterResult harvest(DataverseRequest dataverseRequest, HarvestingClient harvestingClient, Logger hdLogger, DataciteHarvesterParams params) throws ImportException {
Can we add test cases for this method?

2024-09-12 08:14 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/DataciteDOIHarvester.java
> +    private DatasetDao datasetDao;
Do we use this service in this class?

2024-09-18 10:32 UTC, diasf commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/DataciteDOIHarvester.java
>      public HarvesterResult harvest(DataverseRequest dataverseRequest, HarvestingClient harvestingClient, Logger hdLogger, DataciteHarvesterParams params) throws ImportException {
Yep, added some unit tests.

2024-09-18 10:32 UTC, diasf commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/DataciteDOIHarvester.java
> +    private DatasetDao datasetDao;
Removed.

2024-09-19 08:48 UTC, madryk approved these changes

2024-09-20 07:35 UTC, merged