Closes #2509: New notifications UI
CeON/fairchive pull request #2530
Opened 2024-08-06 12:27 UTC by diasf

New UI to manage notifications.

TODO:
* notification filter

Issue: #2509

2024-09-19 10:36 UTC, madryk requested changes

2024-09-19 10:36 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationQuery.java
> +    }
If we are making this a `builder` kind of class then I think that we should block creating the object outside of it by adding private constructor.

2024-09-19 10:36 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationQuery.java
> +    boolean ascending;
Any reason why this is not `private`? Do we need it to be `package private`?

2024-09-19 10:36 UTC, madryk commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationRepository.java
> +            predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("searchLabel")), "%" + queryParam.getSearchLabel().toLowerCase() + "%"));
Do index on `searchLabel` will be used when we lower case it in the query? If yes then ok. If not then I would consider to keep lowercased `searchLabel` in the DB (since we use this field only for searching) and skip lowercasing it here.

2024-09-19 10:36 UTC, madryk commented on dataverse-persistence/src/main/resources/Bundle_pl.properties
> +notification.numSelected=Obecnie wybrano {0} {0,choice,0#powiadomie\u0144|1#powiadomienie|2#powiadomie\u0144}
Depending on the number we will have:
 - `Obecnie wybrano 0 powiadomień` - OK
 - `Obecnie wybrano 1 powiadomienie` - OK
 - `Obecnie wybrano 2 powiadomień` - I think it should be `powiadomienia`
 - `Obecnie wybrano 3 powiadomień` - As above
 - `Obecnie wybrano 4 powiadomień` - As above
 - `Obecnie wybrano 5 powiadomień` - OK

2024-09-19 10:36 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/Index.java
> +    @Path("usernotifications")
I assume that method `GET` is to keep the consistency between other endpoints in `Index`. Is that right? Because endpoint will result in some change in DB. If yes then then ignore this comment

2024-09-20 10:16 UTC, diasf commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationQuery.java
> +    }
Yeah, good point, added private constructor.

2024-09-20 10:16 UTC, diasf commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationQuery.java
> +    boolean ascending;
Made them private.

2024-09-20 10:17 UTC, diasf commented on dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/user/UserNotificationRepository.java
> +            predicates.add(criteriaBuilder.like(criteriaBuilder.lower(root.get("searchLabel")), "%" + queryParam.getSearchLabel().toLowerCase() + "%"));
Setting it to lower case in the db seems actually cleaner to me. I've adjusted that.

2024-09-20 10:18 UTC, diasf commented on dataverse-persistence/src/main/resources/Bundle_pl.properties
> +notification.numSelected=Obecnie wybrano {0} {0,choice,0#powiadomie\u0144|1#powiadomienie|2#powiadomie\u0144}
Corrected.

2024-09-20 10:20 UTC, diasf commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/Index.java
> +    @Path("usernotifications")
Yeah, it's to be consistent with the other endpoints. They're all GET requests despite performing actions/write operations (apart from 2 DELETE which accurately delete things). Didn't want to break that "consistency" for this new one.

2024-09-23 14:52 UTC, madryk approved these changes

2024-09-24 07:40 UTC, merged