Closes #2505: Allow to move multiple datasets at once
CeON/fairchive pull request #2545
Opened 2024-09-04 12:57 UTC by diasf

Allow to select multiple datasets and move them to another dataverse.

Issue: #2505

2024-09-12 11:41 UTC, madryk requested changes

2024-09-12 11:41 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardDatamovePage.java
> +        JsfHelper.addInfoMessage(sb.toString().replaceAll("<br><br>", "<br>"));
`dataverseName` is part of the message and it is something that is provided by the user. Do we have here some kind of protection against xss attack?

2024-09-12 11:41 UTC, madryk commented on dataverse-persistence/src/main/resources/Bundle_pl.properties
> +dashboard.datamove.dataset.message.success.multiple=Zbior\u00F3w danych ({0}) zosta\u0142y pomy\u015Blnie przeniesiony do kolekcji "{1}".<br>
`Zbiorów` -> `Zbiory`?

2024-09-17 08:29 UTC, diasf commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardDatamovePage.java
> +        JsfHelper.addInfoMessage(sb.toString().replaceAll("<br><br>", "<br>"));
Yeah, good point. Changed `dataverse.getName()` to `dataverse.getDisplayName()` which performs html sanitization.

2024-09-17 11:55 UTC, madryk approved these changes

2024-09-17 13:18 UTC, merged