Closes: Fieldset_validator_for_releated_fields
CeON/fairchive pull request #2551
Opened 2024-09-13 10:28 UTC by dkorbel

**What this PR does / why we need it**:
This feature adds additional validator that work for multiply fields.

This is a new validator that works for a set of fields that are related to each other. Based on the value of one field, it can validate a subset of fields for that value.

For example, in a purchase contact information form, we need different values for a company and a person. So, we add a 'select' field where we can choose whose details we need: either a person or a company. Then, we add fields for both individuals and companies. The validator will only validate the fields indicated by the first 'select' field.

**Which issue(s) this PR closes**:
It comes from Fairbirds team.

Example usage:
#datasetField	name	title	validation
	responsible_party	Responsible party	"[{""name"":""standard_input""}]"
	responsible_party_type	Type	"[{""name"":""standard_input""}]"
	responsible_party_person_first_name	First name	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""person""}}]"
	responsible_party_person_surnames	Surname(s)	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""person""}}]"
	responsible_party_organization_name	Organization name	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""organization""}}]"
	responsible_party_organization_address_city	City	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""organization""}}]"
	responsible_party_organization_address_postal-code	Postal code	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""organization""}}]"
	responsible_party_organization_address_administrative-area	Administrative area	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""organization""}}]"
	responsible_party_organization_address_country	Country	"[{""name"":""required_by_value_dependant"",""parameters"":{""context"":[""DATASET""], ""runOnEmpty"":""true"", ""dependantField"": ""responsible_party_type"", ""dependantFieldValue"": ""organization""}}]"
	responsible_party_email_address	Email address	"[{""name"":""standard_input""}]"
	responsible_party_orcid	ORCID	"[{""name"":""standard_input""}]"
#controlledVocabulary	DatasetField	Value	identifier
	responsible_party_type	Person	person
	responsible_party_type	Organization	organization

[releatedFieldValidator.csv](https://github.com/user-attachments/files/16992492/releatedFieldValidator.csv)

2024-09-13 10:54 UTC, sniewczas requested changes

2024-09-13 10:54 UTC, sniewczas commented on dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/RequiredByValueDependantFieldValidatorTest.java
> +public class RequiredByValueDependantFieldValidatorTest {
The build is failing.

```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.269 s <<< FAILURE! - in edu.harvard.iq.dataverse.validation.field.validators.RequiredByValueDependantFieldValidatorTest
[ERROR] edu.harvard.iq.dataverse.validation.field.validators.RequiredByValueDependantFieldValidatorTest  Time elapsed: 0.269 s  <<< ERROR!
org.mockito.exceptions.misusing.NotAMockException: Argument passed to Mockito.mockingDetails() should be a mock, but is an instance of class java.lang.Class!
```

2024-09-13 10:54 UTC, sniewczas commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/RequiredDependantFieldValidator.java
> + * @author Daniel Korbel, Krzysztof Mądry, Sylwester Niewczas
I don't think attributing authorship to us here is appropriate. Let's at least mention the original author first.

2024-09-16 07:55 UTC, sniewczas commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/RequiredByValueDependantFieldValidator.java
> +        if (dependantField.getValidatableValues().stream().anyMatch(actualValue -> StringUtils.equalsIgnoreCase(actualValue, (String) params.get(DEPENDANT_FIELD_VALUE_PARAM)))) {
Nitpick: These super-long lines could use a line break. Let's not force people to scroll vertically.

2024-09-16 14:27 UTC, madryk approved these changes

2024-09-16 15:54 UTC, dkorbel commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/RequiredDependantFieldValidator.java
> + * @author Daniel Korbel, Krzysztof Mądry, Sylwester Niewczas
Sure

2024-09-16 15:54 UTC, dkorbel commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/RequiredByValueDependantFieldValidator.java
> +        if (dependantField.getValidatableValues().stream().anyMatch(actualValue -> StringUtils.equalsIgnoreCase(actualValue, (String) params.get(DEPENDANT_FIELD_VALUE_PARAM)))) {
Sure

2024-09-17 07:30 UTC, sniewczas approved these changes

2024-09-17 11:06 UTC, merged