added support for image preview during upload + fixed reuse banner option.
CeON/fairchive pull request #31
Opened 2019-01-30 15:12 UTC by MrK191

2019-01-31 16:49 UTC, madryk requested changes

2019-01-31 16:49 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/dataverse/banners/NewBannerPage.java
> +                            new DefaultStreamedContent(new ByteArrayInputStream(event.getFile().getContents())));
I think you can use different implementation of `StreamedContent` - `ByteArrayContent`. You won't need
double new operation

2019-01-31 16:49 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/dataverse/banners/dto/BannerMapper.java
> +    private DataverseLocalizedBanner MapToLocalizedBanner(DataverseBanner banner, DataverseLocalizedBannerDto fuDto) {
method names should have first letter lowercased

2019-01-31 16:49 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/dataverse/banners/dto/DataverseLocalizedBannerDto.java
> +    private StreamedContent uploadedDisplayImage;
Are you really sure that you need all of these fields in model class.
We have already 3 ones to store image.
And StreamedContent can store contentType and name.

2019-02-01 13:24 UTC, MrK191 commented on src/main/java/edu/harvard/iq/dataverse/dataverse/banners/dto/DataverseLocalizedBannerDto.java
> +    private StreamedContent uploadedDisplayImage;
In terms of contentType and name it's true, in terms of image fields, another way would be to call some image method which would translate *byte[]* to miniature image or normal sized one.

2019-02-04 14:12 UTC, madryk requested changes

2019-02-04 14:12 UTC, madryk commented on src/test/java/edu/harvard/iq/dataverse/dataverse/banners/dto/BannerMapperTest.java
> +        ;
Not needed semicolon

2019-02-04 14:12 UTC, madryk commented on src/main/java/edu/harvard/iq/dataverse/dataverse/banners/dto/BannerMapper.java
>          if (isBannerReused(fuDto)) {
Do we need to rely on what is in `fuDto.getFile()`? Is there is some situation when `fuDto.getDisplayedImage()` will be something different than `fuDto.getFile()`?

2019-02-05 13:27 UTC, madryk approved these changes

2019-02-05 15:23 UTC, merged