Closes: #384 ManageGroups CRUD to separate service
CeON/fairchive pull request #389
Opened 2019-10-04 15:31 UTC by dbojanek

2019-10-04 15:32 UTC, dbojanek commented
Please take a look before i start writing tests.

2019-10-14 12:20 UTC, madryk requested changes

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/resources/config/dataverse.default.properties
> +ProvCollectionEnabled=true
Do we want to keep this enabled?

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
> +    private DataversePage dvpage;
Probably we can remove this page field

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsCRUDService.java
> +    public ExplicitGroup update(ExplicitGroup selectedGroup, List<RoleAssignee> selectedGroupAddRoleAssignees)
Names of method arguments are misleading - we don't have any "selected" context (selected is ui specific). I would go for something like: `group` and `newRoleAssignees` or `roleAssigneesToAdd`

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
> +                            RoleAssigneeServiceBean roleAssigneeService, PermissionsWrapper permissionsWrapper,
RoleAssigneeServiceBean have MockRoleAssigneeServiceBean implementation in tests. Changing from ejb to inject for it will probably break integration tests. Probably we want `MockRoleAssigneeServiceBean` to be annotated with `@TestBean`

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
>              logger.log(Level.SEVERE, "Error saving role: " + ex.getMessage(), ex);
It doesn't seem that we can reach this exception. And even if we can then assuming that role couldn't be saved is very misleading. I would remove this catch and loosen catching `CommandException` to catching `Exception`

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
>              logger.log(Level.SEVERE, "Error saving role: " + ex.getMessage(), ex);
The same as above

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
>              logger.log(Level.SEVERE, "Error saving role: " + ex.getMessage(), ex);
If we loose catch of CommandException to Exception then catching GroupException is kind of obsolete. Handling of both exceptions is the same

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsPage.java
>              JsfHelper.JH.addMessage(FacesMessage.SEVERITY_ERROR, BundleUtil.getStringFromBundle("dataverse.manageGroups.save.fail"),
I would merge GroupException with CommandException here. Distinction between dataverse.manageGroups.edit.fail and dataverse.manageGroups.save.fail messages is kind of mysterious knowledge that is no way helpful for the user. And for developers there is stacktrace

2019-10-14 12:20 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsCRUDService.java
> +public class ManageGroupsCRUDService {
Can we try the methods to use Try.of in this service?

2019-10-16 07:19 UTC, dbojanek commented on dataverse-webapp/src/main/resources/config/dataverse.default.properties
> +ProvCollectionEnabled=true
I'd say untill on production we shouldn't hide functionalities. Keeping this enabled will give us more wholly view on the app while still in development.
I'd keep this enabled

2019-10-16 07:24 UTC, dbojanek commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ManageGroupsCRUDService.java
> +    public ExplicitGroup update(ExplicitGroup selectedGroup, List<RoleAssignee> selectedGroupAddRoleAssignees)
You're right.

2019-10-18 14:55 UTC, madryk approved these changes

2019-10-21 07:00 UTC, merged