Closes #362: Correct layout related things on main dataverse page
CeON/fairchive pull request #392
Opened 2019-10-10 10:03 UTC by sudmar

- increased distance between dataverse logo and name on the carousel
- checkboxes are now greyed out when disabled
- fixed the alignment of the harvested/linked icons
- fixed the alignment of the dataverse icons (replaced with an SVG image)
- fixed the look of the error messages

2019-10-14 11:06 UTC, madryk requested changes

2019-10-14 11:06 UTC, madryk commented on dataverse-webapp/src/main/webapp/resources/vecler/theme.scss
>  $table-row-hover: #e6eff2;
Harvested and linked icons on file are grey
![harvested](https://user-images.githubusercontent.com/8190961/66746036-fe3ac600-ee80-11e9-9486-cd5d527e35be.png)

2019-10-14 11:06 UTC, madryk commented on dataverse-webapp/src/main/webapp/resources/vecler/theme.scss
>  $table-row-hover: #e6eff2;
I have a feeling that linked/harvested icons are bigger than dataset/file icons.

2019-10-15 08:14 UTC, sudmar commented on dataverse-webapp/src/main/webapp/resources/vecler/theme.scss
>  $table-row-hover: #e6eff2;
Fixed

2019-10-15 08:14 UTC, sudmar commented on dataverse-webapp/src/main/webapp/resources/vecler/theme.scss
>  $table-row-hover: #e6eff2;
Made them a bit smaller

2019-10-15 11:05 UTC, madryk approved these changes

2019-10-15 11:10 UTC, merged