Closes #417: Fix tags modal window on some pages.
CeON/fairchive pull request #444
Opened 2019-11-07 12:13 UTC by sudmar

2019-11-12 10:26 UTC, MrK191 requested changes
There is still something wrong on Replace and Edit single file page [pictures](https://imgur.com/a/aXhYAs4).

2019-11-14 05:43 UTC, sudmar commented
I'm not able to reproduce this issue. It looks like in your case the .css file has not been regenerated and/or updated by the browser.

Can you check it again, making sure that a fresh .css file is generated from the source .scss, and reloading the page using Ctrl+F5 to force the browser to delete the cached stylesheet?

2019-11-14 09:34 UTC, MrK191 commented
Ah you are right, my IJ plugin didn't work for some reason.

2019-11-14 09:34 UTC, MrK191 approved these changes

2019-11-14 09:42 UTC, merged