Changed language of email messages, now they are based of user setting.
CeON/fairchive pull request #520
Opened 2019-12-06 14:11 UTC by MrK191

2019-12-06 15:18 UTC, madryk requested changes

2019-12-06 15:18 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java
> +        return (AuthenticatedUser) session.getUser();
The whole point was to use language of user that will receive the email - not language of the user that initiates the action

2019-12-11 12:46 UTC, wtr-icm approved these changes

2019-12-11 12:46 UTC, wtr-icm commented on dataverse-persistence/src/main/resources/Bundle_en.properties
> +notification.email.createDataverse=Your new dataverse named {0} (view at {1} ) was created in {2} (view at {3}). To learn more about what you can do with your dataverse, check out the Dataverse Manag
Do we want to preserve this space between `{1}` and `)`?

2019-12-11 12:46 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java
> +                                                      notificationDto.getNotificationReceiver().getNotificationsLanguage(),
Maybe we can put this `notificationDto.getNotificationReceiver().getNotificationsLanguage()` into some variable, and reduce repetitions in following lines?

2019-12-11 12:52 UTC, MrK191 commented on dataverse-persistence/src/main/resources/Bundle_en.properties
> +notification.email.createDataverse=Your new dataverse named {0} (view at {1} ) was created in {2} (view at {3}). To learn more about what you can do with your dataverse, check out the Dataverse Manag
Hmm, I will ask @wfenrich about it.

2019-12-11 14:12 UTC, wtr-icm approved these changes

2019-12-12 09:01 UTC, madryk approved these changes

2019-12-13 09:21 UTC, merged