Jhove relocation
CeON/fairchive pull request #54
Opened 2019-02-22 14:46 UTC by MrK191

2019-02-22 15:08 UTC, madryk requested changes

2019-02-22 15:08 UTC, madryk commented on conf/jhove/jhove.conf
> +https://gist.githubusercontent.com/MrK191/d78b0aee92c4e260372565aeae38b5eb/raw/89b8b0ee230b32b6b7fd020482a072e7848792eb/jhoveConfig.xsd"">
Double `"` sign at the end - probably this xml is unparseable

2019-02-22 15:08 UTC, madryk commented on conf/jhove/jhove.conf
> +https://gist.githubusercontent.com/MrK191/d78b0aee92c4e260372565aeae38b5eb/raw/89b8b0ee230b32b6b7fd020482a072e7848792eb/jhoveConfig.xsd"">
As we already depend on what's on github, maybe we should jump to xsd in jhove project on github.

https://raw.githubusercontent.com/openpreserve/jhove/v1.11/classes/edu/harvard/hul/ois/jhove/jhoveConfig.xsd

It is identical. What do you think?

I found also xsd hosted on harvard:

http://hul.harvard.edu/ois/xml/xsd/jhove/1.4/jhoveConfig.xsd

2019-02-22 15:56 UTC, MrK191 commented on conf/jhove/jhove.conf
> +https://gist.githubusercontent.com/MrK191/d78b0aee92c4e260372565aeae38b5eb/raw/89b8b0ee230b32b6b7fd020482a072e7848792eb/jhoveConfig.xsd"">
ah parsing error, the field in test resources is correct, will fix.
If it will work then why not, better than holding on my own repo.

2019-02-28 09:36 UTC, madryk approved these changes

2019-02-28 09:36 UTC, merged