Closes #642: Cumulative Charts and other changes to metrics
CeON/fairchive pull request #704
Opened 2020-02-28 07:08 UTC by dbojanek

2020-03-02 08:15 UTC, madryk requested changes

2020-03-02 08:15 UTC, madryk commented on dataverse-persistence/src/main/resources/Bundle_pl.properties
> +metrics.chart.files.yAxis.label=Liczba plik\u00F3w
I personally wouldn't make so descriptive yAxis label's. And make it simple: 'Pliki` (and do the same for others yAxis labels)

2020-03-02 08:15 UTC, madryk commented on dataverse-webapp/src/main/webapp/metrics.xhtml
> +                            <f:selectItem itemLabel="#{bundle['metrics.section.datasets.radiobutton.monthly.label']}" itemValue="MONTH"/>
I think that If we would have cumulative as first option, yearly as second and monthly as third - the whole thing would be more understandable

2020-03-02 08:19 UTC, dbojanek commented on dataverse-persistence/src/main/resources/Bundle_pl.properties
> +metrics.chart.files.yAxis.label=Liczba plik\u00F3w
These were specified like that by @wfenrich so I guess we should as Wojtek?

2020-03-03 11:34 UTC, madryk approved these changes

2020-03-03 12:28 UTC, merged