Closes #735: Moving dataset from UI
CeON/fairchive pull request #752
Opened 2020-03-10 14:04 UTC by wtr-icm

2020-03-10 14:06 UTC, wtr-icm commented on dataverse-persistence/src/main/resources/Bundle_en.properties
> +
Both bundles are not in the final stage at the moment.

2020-03-10 14:07 UTC, wtr-icm commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardDatamovePage.java
> +package edu.harvard.iq.dataverse.dashboard;
This is moved from Dataverse 4.11 with a heavy refactor

2020-03-17 12:11 UTC, madryk requested changes

2020-03-17 12:11 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-datamove.xhtml
> +                                        <p:message for="sourceDatasetMenu"/>
In most places we show validation messages as text only, so I would add `display="text"` argument for this `p:message`

2020-03-17 12:11 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-datamove.xhtml
> +                                        <p:message for="destinationDataverseMenu"/>
same comment as above

2020-03-17 12:11 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-datamove.xhtml
> +                            <f:param name="DO_DATAMOVE_VALIDATION" value="true"/>
Not sure if this param is ever used

2020-03-17 12:11 UTC, madryk commented on dataverse-webapp/src/main/webapp/dashboard-datamove.xhtml
> +                            -->
Not helpful comment - I would get rid of it

2020-03-17 12:11 UTC, madryk commented on dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardDatamovePage.java
> +            DataverseRequest dataverseRequest = new DataverseRequest(authenticatedUser, request);
You can use `DataverseRequestServiceBean` to obtain this object. That way you can omit injecting `HttpServletRequest` and saving `authenticatedUser` as a class field

2020-03-18 09:49 UTC, madryk approved these changes

2020-03-18 10:38 UTC, merged